# Generated by Django 5.2.7 on 2025-11-04 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='URL del endpoint de push del navegador', unique=True)),
                ('p256dh', models.TextField(help_text='Clave pública del cliente para encriptación')),
                ('auth', models.TextField(help_text='Token de autenticación del cliente')),
                ('user_agent', models.CharField(blank=True, help_text='User agent del navegador', max_length=500)),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Si la suscripción está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_notificacion', models.DateTimeField(blank=True, help_text='Fecha de la última notificación enviada', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'db_table': 'push_subscriptions',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra_exitosa', 'Compra Exitosa'), ('cambio_estado', 'Cambio de Estado'), ('promocion', 'Promoción'), ('otro', 'Otro')], db_index=True, max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, help_text='Datos adicionales de la notificación', null=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], db_index=True, default='pendiente', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.pushsubscription')),
            ],
            options={
                'verbose_name': 'Notificación Enviada',
                'verbose_name_plural': 'Notificaciones Enviadas',
                'db_table': 'notificaciones_enviadas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['usuario', 'activa'], name='push_subscr_usuario_525c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['-fecha_creacion'], name='push_subscr_fecha_c_3c41d5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionenviada',
            index=models.Index(fields=['usuario', '-fecha_envio'], name='notificacio_usuario_28dca5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionenviada',
            index=models.Index(fields=['tipo', '-fecha_envio'], name='notificacio_tipo_7629ac_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionenviada',
            index=models.Index(fields=['estado'], name='notificacio_estado_9de54f_idx'),
        ),
    ]
