# Generated by Django 5.2.7 on 2025-10-28 15:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('compra', '0002_compra_descuento_aplicado'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto Fijo')], default='porcentaje', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descuento_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para uso ilimitado', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo', 'activa'], name='promociones_codigo_31abd2_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='promociones_fecha_i_a974ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='DevolucionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('devolucion', 'Devolución con Reembolso'), ('cambio', 'Cambio por otro Producto')], default='devolucion', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('monto_reembolso', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('respuesta_admin', models.TextField(blank=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='clientes.cliente')),
                ('compra_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='compra.compraitem')),
                ('producto_reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usado_en_cambios', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', '-fecha_solicitud'], name='devolucione_estado_badc6f_idx'), models.Index(fields=['cliente', '-fecha_solicitud'], name='devolucione_cliente_d4e6d6_idx')],
            },
        ),
    ]
