# Generated by Django 5.2.7 on 2025-10-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='pago_estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='vendedor',
        ),
    ]
