# Generated by Django 5.2.7 on 2025-10-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_descuento_aplicado'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='promociones.promocion'),
        ),
    ]
