# Generated by Django 5.2.7 on 2025-10-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_remove_compra_estado_remove_compra_pago_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
