# Generated by Django 5.2.7 on 2025-10-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Generar Reporte con IA',
                'verbose_name_plural': 'Generar Reportes con IA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Consulta en lenguaje natural')),
                ('prompt_interpretado', models.JSONField(blank=True, null=True, verbose_name='Interpretación del prompt')),
                ('sql_generado', models.TextField(blank=True, verbose_name='SQL generado')),
                ('formato_salida', models.CharField(choices=[('pantalla', 'Pantalla'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pantalla', max_length=20)),
                ('resultado', models.JSONField(blank=True, null=True, verbose_name='Resultado de la consulta')),
                ('error', models.TextField(blank=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tiempo_ejecucion', models.FloatField(blank=True, null=True, verbose_name='Tiempo de ejecución (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta IA',
                'verbose_name_plural': 'Consultas IA',
                'db_table': 'consultas_ia',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
