# Generated by Django 5.2.7 on 2025-10-28 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0002_reportegenerado_consultaia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaia',
            name='formato_salida',
            field=models.CharField(choices=[('pantalla', 'Pantalla'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], db_index=True, default='pantalla', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultaia',
            name='prompt',
            field=models.TextField(db_index=True, verbose_name='Consulta en lenguaje natural'),
        ),
        migrations.AddIndex(
            model_name='consultaia',
            index=models.Index(fields=['usuario', '-fecha_consulta'], name='idx_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='consultaia',
            index=models.Index(fields=['formato_salida', '-fecha_consulta'], name='idx_formato_fecha'),
        ),
    ]
