# Generated by Django 5.2.7 on 2025-10-26 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado (si el cliente tiene cuenta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['usuario'], name='clientes_usuario_db400c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['asignado_a'], name='clientes_asignad_73d6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['-fecha_creacion'], name='clientes_fecha_c_8b9ce5_idx'),
        ),
    ]
